hransac:
  ros__parameters:
    max_loop: 100
    threshold: 0.05
    min_samples: 10
    detect_line: 5
    min_theta: -90.0
    max_theta: 90.0
    sampling_rate: 1
    tf_y: 0.237673  # LiDARの中心から機体の中心の距離
    visu_line: true
    court: true  # trueで赤コート、falseで青コート
