pid:
  ros__parameters:
    linear_kp: 1.0
    linear_ki: 0.0
    linear_kd: 0.0
    angular_kp: 0.05
    angular_ki: 0.0
    angular_kd: 0.0
    max_linear_velocity: 0.5
    max_angular_velocity: 0.1
    arrival_threshold: 0.05
    theta_threshold: 0.05
    wait_time: 1
    red_csv: /home/yuki/ros2_ws/src/uni_tes/path/red.csv
    blue_csv: /home/yuki/ros2_ws/src/uni_tes/path/blue.csv
